x-base: &base
  build:
    context: .
    dockerfile: Dockerfile.dev
  image: rcbook
  env_file: .env
  command: npm run dev
  restart: unless-stopped
  volumes:
    - .:/srv/rcbook:cached
    - /srv/rcbook/node_modules

services:
  # mongo:
  #   image: mongo:latest
  #   restart: always
  #   # environment:
  #   #   MONGO_INITDB_ROOT_USERNAME: root
  #   #   MONGO_INITDB_ROOT_PASSWORD: example
  #   ports: 
  #     - 27017:27017
  #   volumes:
  #     - type: volume
  #       source: MONGO_DATA
  #       target: /data/db
  #     - type: volume
  #       source: MONGO_CONFIG
  #       target: /data/configdb

  # redis:
  #   image: redis:latest
  #   container_name: grindor_redis
  #   hostname: redis
  #   environment:
  #     # ALLOW_EMPTY_PASSWORD is recommended only for development.
  #     - ALLOW_EMPTY_PASSWORD=yes
  #     - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redis_data:/bitnami/redis/data

  server:
    <<: *base
    hostname: server
    environment:
      MODE: server
    ports:
      - 8000:8000

# volumes:
#   redis_data:
#     driver: local
#   MONGO_DATA:
#     name: MONGO_DATA
#   MONGO_CONFIG:
#     name: MONGO_CONFIG